SSH_USERNAME=steven
SERVER_SSH_IP=192.168.86.100
SERVER_TEST_IP=192.168.86.100
CLIENT_SSH_IP=192.168.86.200
PROTOCOL=tcp
PORT=9001
DURATION=30
METRICS_INTERVAL=1
PATH_TO_SSH_CERT=/home/steven/.ssh/id_rsa.pub
RESULTS_FILE_PREFIX=wireguard
NIC_NAME=ens34

./run_benchmark.bash $SSH_USERNAME $SERVER_SSH_IP $SERVER_TEST_IP $CLIENT_SSH_IP $PROTOCOL $PORT $DURATION $METRICS_INTERVAL $PATH_TO_SSH_CERT $RESULTS_FILE_PREFIX $NIC_NAME
