SSH_USERNAME=steven
SERVER_SSH_IP=127.0.0.1
SERVER_TEST_IP=127.0.0.1
CLIENT_SSH_IP=127.0.0.1
PROTOCOL=tcp
PORT=9001
DURATION=30
METRICS_INTERVAL=1
PATH_TO_SSH_CERT=/home/steven/.ssh/id_rsa.pub
RESULTS_FILE_PREFIX=local

./run_benchmark.bash $SSH_USERNAME $SERVER_SSH_IP $SERVER_TEST_IP $CLIENT_SSH_IP $PROTOCOL $PORT $DURATION $METRICS_INTERVAL $PATH_TO_SSH_CERT $RESULTS_FILE_PREFIX 
